/*
 * Dataspace Connector
 * IDS Connector reference implementation
 *
 * The version of the OpenAPI document: 8.0.2
 * Contact: support@sovity.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.net.URI;
import org.openapitools.client.model.AuthenticationDesc;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ArtifactDesc
 */
public class ArtifactDescTest {
    private final ArtifactDesc model = new ArtifactDesc();

    /**
     * Model tests for ArtifactDesc
     */
    @Test
    public void testArtifactDesc() {
        // TODO: test ArtifactDesc
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'remoteId'
     */
    @Test
    public void remoteIdTest() {
        // TODO: test remoteId
    }

    /**
     * Test the property 'remoteAddress'
     */
    @Test
    public void remoteAddressTest() {
        // TODO: test remoteAddress
    }

    /**
     * Test the property 'accessUrl'
     */
    @Test
    public void accessUrlTest() {
        // TODO: test accessUrl
    }

    /**
     * Test the property 'basicAuth'
     */
    @Test
    public void basicAuthTest() {
        // TODO: test basicAuth
    }

    /**
     * Test the property 'apiKey'
     */
    @Test
    public void apiKeyTest() {
        // TODO: test apiKey
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

    /**
     * Test the property 'automatedDownload'
     */
    @Test
    public void automatedDownloadTest() {
        // TODO: test automatedDownload
    }

}
