/*
 * Dataspace Connector
 * IDS Connector reference implementation
 *
 * The version of the OpenAPI document: 8.0.2
 * Contact: support@sovity.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OfferedResourceDesc
 */
public class OfferedResourceDescTest {
    private final OfferedResourceDesc model = new OfferedResourceDesc();

    /**
     * Model tests for OfferedResourceDesc
     */
    @Test
    public void testOfferedResourceDesc() {
        // TODO: test OfferedResourceDesc
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'keywords'
     */
    @Test
    public void keywordsTest() {
        // TODO: test keywords
    }

    /**
     * Test the property 'publisher'
     */
    @Test
    public void publisherTest() {
        // TODO: test publisher
    }

    /**
     * Test the property 'language'
     */
    @Test
    public void languageTest() {
        // TODO: test language
    }

    /**
     * Test the property 'license'
     */
    @Test
    public void licenseTest() {
        // TODO: test license
    }

    /**
     * Test the property 'sovereign'
     */
    @Test
    public void sovereignTest() {
        // TODO: test sovereign
    }

    /**
     * Test the property 'endpointDocumentation'
     */
    @Test
    public void endpointDocumentationTest() {
        // TODO: test endpointDocumentation
    }

    /**
     * Test the property 'samples'
     */
    @Test
    public void samplesTest() {
        // TODO: test samples
    }

    /**
     * Test the property 'paymentMethod'
     */
    @Test
    public void paymentMethodTest() {
        // TODO: test paymentMethod
    }

}
