/*
 * Dataspace Connector
 * IDS Connector reference implementation
 *
 * The version of the OpenAPI document: 8.0.2
 * Contact: support@sovity.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.DapsView;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PagedModelDapsViewEmbedded
 */
public class PagedModelDapsViewEmbeddedTest {
    private final PagedModelDapsViewEmbedded model = new PagedModelDapsViewEmbedded();

    /**
     * Model tests for PagedModelDapsViewEmbedded
     */
    @Test
    public void testPagedModelDapsViewEmbedded() {
        // TODO: test PagedModelDapsViewEmbedded
    }

    /**
     * Test the property 'daps'
     */
    @Test
    public void dapsTest() {
        // TODO: test daps
    }

}
