/*
 * Dataspace Connector
 * IDS Connector reference implementation
 *
 * The version of the OpenAPI document: 8.0.2
 * Contact: support@sovity.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TypedLiteral
 */
public class TypedLiteralTest {
    private final TypedLiteral model = new TypedLiteral();

    /**
     * Model tests for TypedLiteral
     */
    @Test
    public void testTypedLiteral() {
        // TODO: test TypedLiteral
    }

    /**
     * Test the property 'atValue'
     */
    @Test
    public void atValueTest() {
        // TODO: test atValue
    }

    /**
     * Test the property 'atType'
     */
    @Test
    public void atTypeTest() {
        // TODO: test atType
    }

    /**
     * Test the property 'atLanguage'
     */
    @Test
    public void atLanguageTest() {
        // TODO: test atLanguage
    }

}
