/*
 * Dataspace Connector
 * IDS Connector reference implementation
 *
 * The version of the OpenAPI document: 8.0.2
 * Contact: support@sovity.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.openapitools.client.model.AuthenticationDesc;
import org.openapitools.client.model.DatabaseDataSourceDesc;
import org.openapitools.client.model.RestDataSourceDesc;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Update7Request
 */
public class Update7RequestTest {
    private final Update7Request model = new Update7Request();

    /**
     * Model tests for Update7Request
     */
    @Test
    public void testUpdate7Request() {
        // TODO: test Update7Request
    }

    /**
     * Test the property 'basicAuth'
     */
    @Test
    public void basicAuthTest() {
        // TODO: test basicAuth
    }

    /**
     * Test the property 'apiKey'
     */
    @Test
    public void apiKeyTest() {
        // TODO: test apiKey
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'driverClassName'
     */
    @Test
    public void driverClassNameTest() {
        // TODO: test driverClassName
    }

}
