/*
 * Dataspace Connector
 * IDS Connector reference implementation
 *
 * The version of the OpenAPI document: 8.0.2
 * Contact: support@sovity.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.gateai.gateconnect.client.api;

import eu.gateai.gateconnect.client.ApiException;
import org.openapitools.client.model.ContractRuleDesc;
import org.openapitools.client.model.ContractRuleView;
import org.openapitools.client.model.PagedModelContractRuleView;
import org.openapitools.client.model.PagedModelContractView;
import java.net.URI;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RulesApi
 */
@Disabled
public class RulesApiTest {

    private final RulesApi api = new RulesApi();

    /**
     * Add a list of children to a base resource.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addResourcesTest() throws ApiException {
        UUID id = null;
        List<URI> URI = null;
        PagedModelContractView response = api.addResources(id, URI);
        // TODO: test validations
    }

    /**
     * Create a base resource.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void create1Test() throws ApiException {
        ContractRuleDesc contractRuleDesc = null;
        ContractRuleView response = api.create1(contractRuleDesc);
        // TODO: test validations
    }

    /**
     * Delete a base resource by id.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void delete1Test() throws ApiException {
        UUID id = null;
        api.delete1(id);
        // TODO: test validations
    }

    /**
     * Get a base resource by id.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void get1Test() throws ApiException {
        UUID id = null;
        ContractRuleView response = api.get1(id);
        // TODO: test validations
    }

    /**
     * Get a list of base resources with pagination.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAll1Test() throws ApiException {
        Integer page = null;
        Integer size = null;
        PagedModelContractRuleView response = api.getAll1(page, size);
        // TODO: test validations
    }

    /**
     * Get all children of a base resource with pagination.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getResourceTest() throws ApiException {
        UUID id = null;
        Integer page = null;
        Integer size = null;
        PagedModelContractView response = api.getResource(id, page, size);
        // TODO: test validations
    }

    /**
     * Remove a list of children from a base resource.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void removeResourcesTest() throws ApiException {
        UUID id = null;
        List<URI> URI = null;
        api.removeResources(id, URI);
        // TODO: test validations
    }

    /**
     * Replace the children of a base resource.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void replaceResourcesTest() throws ApiException {
        UUID id = null;
        List<URI> URI = null;
        api.replaceResources(id, URI);
        // TODO: test validations
    }

    /**
     * Update a base resource by id.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void update1Test() throws ApiException {
        UUID id = null;
        ContractRuleDesc contractRuleDesc = null;
        ContractRuleView response = api.update1(id, contractRuleDesc);
        // TODO: test validations
    }

}
